# Generated by Django 3.2.23 on 2023-11-07 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0002_productos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Productos',
        ),
    ]
